language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - composer test
